server:
  port: 8080

spring:
  application:
    name: basedata

eureka:
  instance:
    #以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
info:
  app:
    name: ${spring.application.name}