server:
  port: 8081

spring:
  application:
    name: producer-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root

eureka:
  instance:
    #以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8761/eureka

#用于审计接口  actuator/info 返回信息
info:
  app:
    name: ${spring.application.name}

feign:
  hystrix:
    enabled: true