spring:
  application:
    name: nacos-tsst
  cloud:
    nacos:
      discovery:
        #nacos服务的地址:端口号
        server-addr: 127.0.0.1:8848
        #nacos命名空间的id
        namespace: 6e65de9c-9069-4d05-8c20-2f94602163aa
      config:
        server-addr: 127.0.0.1:8848
        namespace: 6e65de9c-9069-4d05-8c20-2f94602163aa
        #nacos配置中心需要的文件后缀,目前仅支持ymal和properties
        file-extension: yaml
        #nacos配置中心文件名
        prefix: api-hdys-durid-sys

server:
  port: 8080

